spring.application.name=demo

spring.thymeleaf.cache=false

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB

hospital.name=Benh vien Da khoa Quoc te Rikkei
hospital.hotline=1900-1234
#1. Spring Boot qu?n lý c?u hình m?c ??nh nh? th? nào?
#Spring Boot ho?t ??ng theo tri?t lý "Convention over Configuration" (Quy ??c thay vì c?u hình).
#Khi b?n thêm spring-boot-starter-web, Spring Boot s? tìm các file c?u hình m?c ??nh ???c ?óng gói s?n trong các th? vi?n (th??ng là các file .jar c?a Spring Boot Autoconfigure).
#Ví d?: N?u không nói gì, nó m?c ??nh l?y server.port = 8080 t? các l?p Java c?u hình n?i b?.
#C? ch? ?u tiên: Spring Boot cho phép b?n ghi ?è các thông s? này theo th? t? ?u tiên. File application.properties n?m trong th? m?c src/main/resources có ?u tiên cao h?n các c?u hình m?c ??nh bên trong th? vi?n.

#2. Tìm danh sách c?u hình này ? ?âu?
#B?n có th? tìm th?y toàn b? danh sách các thu?c tính mà Spring Boot h? tr? t?i:
#Tài li?u chính th?c: Trang ch? Spring Common Application Properties. ?ây là "t? ?i?n" ??y ?? nh?t.
#Trong IDE: N?u b?n dùng IntelliJ IDEA b?n Ultimate, khi gõ trong file .properties, nó s? t? ??ng g?i ý (autocomplete) các c?u hình này.
#Mã ngu?n: Tìm trong file spring-configuration-metadata.json n?m bên trong các th? vi?n Spring Boo


# 1. Thay doi cong mang (Port)
server.port=8081
# 2. Dat duong dan goc (Context Path)
# Sau khi cau hinh, URL truy cap se la: http://localhost:8081/api/v1/
server.servlet.context-path=/api/v1

file.upload-dir=${user.home}/rikkei-uploads/
