spring.application.name=demo

spring.thymeleaf.cache=false

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB

hospital.name=Benh vien Da khoa Quoc te Rikkei
hospital.hotline=1900-1234

#1. Spring Boot quan ly cau hinh mac dinh nhu the nao?
#Triet ly: Spring Boot hoat dong theo triet ly "Convention over Configuration" (Quy uoc thay vi cau hinh).
#Cach thuc: Khi ban them spring-boot-starter-web, Spring Boot se tim cac file cau hinh mac dinh duoc dong goi san trong cac thu vien (thuong la cac file .jar cua Spring Boot Autoconfigure).
#Vi du Neu khong thiet lap gi, no se mac dinh lay server.port = 8080 tu cac lop Java cau hinh noi bo.
#Co che uu tien: Spring Boot cho phep ban ghi de cac thong so nay theo thu tu uu tien. File application.properties nam trong thu muc src/main/resources co uu tien cao hon cac cau hinh mac dinh ben trong thu vien.

#2. Tim danh sach cau hinh nay o dau?
#Ban co the tim thay toan bo danh sach cac thuoc tinh ma Spring Boot ho tro tai:
#Tai lieu chinh thuc: Trang chu Spring Common Application Properties. Day la "tu dien" day du nhat.
#Trong IDE: Neu ban dung IntelliJ IDEA ban Ultimate, khi go trong file .properties, no se tu dong goi y (autocomplete) cac cau hinh nay.
#Ma nguon: Tim trong file spring-configuration-metadata.json nam ben trong cac thu vien Spring Boot.


# 1. Thay doi cong mang (Port)
server.port=8081
# 2. Dat duong dan goc (Context Path)
# Sau khi cau hinh, URL truy cap se la: http://localhost:8081/api/v1/
server.servlet.context-path=/api/v1

file.upload-dir=${user.home}/rikkei-uploads/
